data "gigavuecore_get_all_correlated_alarms" "example" {
  acknowledged     = "example"
  acknowledgedby   = "example"
  alias            = "example"
  cluster_id       = "example"
  device_ip        = "example"
  end_time         = "example"
  hostname         = "example"
  page             = "example"
  resource_id      = "example"
  resource_type    = "example"
  severity         = "example"
  sort             = "example"
  start_time       = "example"
  suppressed       = "example"
  type             = "example"
  unacknowledgedby = "example"
}
