data "gigavuecore_get_correlated_alarms_count_by_parameter" "example" {
  acknowledged     = "example"
  acknowledgedby   = "example"
  alias            = "example"
  cluster_id       = "example"
  device_ip        = "example"
  end_time         = "example"
  group_by         = "severity"
  hostname         = "example"
  resource_id      = "example"
  resource_type    = "example"
  severity         = "example"
  start_time       = "example"
  suppressed       = "example"
  type             = "example"
  unacknowledgedby = "example"
}
