data "gigavuecore_get_all_external_trap_receiver" "example" {
  alias          = "example"
  auth_protocol  = "example"
  community      = "example"
  ip_address     = "example"
  page           = "example"
  priv_protocol  = "example"
  security_level = "example"
  snmp_port      = "example"
  snmp_retries   = "example"
  snmp_timeout   = "example"
  snmp_version   = "example"
  sort           = "example"
  user_name      = "example"
}
