data "gigavuecore_get_upgrade_summary" "example" {
  activate_info = "example"
  activate_stage = "example"
  chassis_oper_status = "example"
  cluster_id = "example"
  fetch_info = "example"
  fetch_stage = "example"
  health_state = "example"
  hostname = "example"
  install_info = "example"
  install_stage = "example"
  last_executed_task = "example"
  licensed = "example"
  model = "example"
  page = "example"
  role = "example"
  serial_number = "example"
  sort = "example"
  sw_version = "example"
  tags = "example"
  task_status = "example"
  uboot_version = "example"
  verify_info = "example"
  verify_stage = "example"
}
