action "gigavuecore_replace_fabric_map_with_last_update_timestamp_validation" "example" {
  config {
    alias = "example"
    ap_rules = null
    body_alias = "example"
    cluster_id = "example"
    comment = "example"
    dst_ports = [ "example" ]
    egress_gigastream = [ "example" ]
    enable = true
    encap_tunnel = "example"
    flex_inline = null
    flex_inline_failover = "example"
    flex_inline_vlan_id = 1
    flow_rules = null
    flow_sample5_g_overlap_rules = null
    flow_sample5_g_rules = null
    flow_sample_diameter_rules = null
    flow_sample_overlap_rules = null
    flow_sample_rules = null
    flow_sample_sip_rules = null
    flow_whitelist5_g_overlap_rules = null
    flow_whitelist5_g_rules = null
    flow_whitelist_overlap_rules = null
    flow_whitelist_rules = null
    fstype = null
    gs_rules = null
    gsop = "example"
    health_state = "example"
    health_state_reasons = null
    inline_traffic_path = "example"
    inline_traffic_type = "example"
    ip_rewrite = null
    mod_time = 1
    null_dst_port = true
    order = 1
    rewrite = null
    roles = null
    rule_matching = "example"
    rules = null
    rx_cluster_ports = [ "example" ]
    src_ports = [ "example" ]
    sub_type = "example"
    traffic_type = "example"
    tx_cluster_ports = [ "example" ]
    type = "example"
    updated_time = 1.0
    vlan_tag = null
  }
}
