package provider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
)
import (
	client "github.com/gigavuecore/terraform-provider-gigavuecore/internal/client"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// Compile-time interface assertion.
var (
	_ datasource.DataSource              = (*GetTopovizExternalDevicesDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*GetTopovizExternalDevicesDataSource)(nil)
)

// GetTopovizExternalDevicesDataSource is the generated Terraform data source implementation.
type GetTopovizExternalDevicesDataSource struct {
	client *client.Client
}

// GetTopovizExternalDevicesDataSourceModel describes the data source state shape.
type GetTopovizExternalDevicesDataSourceModel struct {
	Category       types.String `tfsdk:"category"`
	DiscoveredType types.String `tfsdk:"discovered_type" json:"discoveredType"`
	Items          types.List   `tfsdk:"items"`
	Model          types.String `tfsdk:"model"`
	NodeAlias      types.String `tfsdk:"node_alias" json:"nodeAlias"`
	Page           types.String `tfsdk:"page"`
	Sort           types.String `tfsdk:"sort"`
	Type           types.String `tfsdk:"type"`
	Vendor         types.String `tfsdk:"vendor"`
}

// NewGetTopovizExternalDevicesDataSource returns a new instance of the generated data source.
func NewGetTopovizExternalDevicesDataSource() datasource.DataSource {
	return &GetTopovizExternalDevicesDataSource{}
}

// Metadata returns the data source type name.
func (d *GetTopovizExternalDevicesDataSource) Metadata(_ context.Context, _ datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "gigavuecore_get_topoviz_external_devices"
}

// Schema returns the data source schema.
func (d *GetTopovizExternalDevicesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{MarkdownDescription: "Loads all external devices in the topology", Attributes: map[string]schema.Attribute{"category": schema.StringAttribute{MarkdownDescription: "Category of devices", Optional: true}, "discovered_type": schema.StringAttribute{Optional: true}, "items": schema.ListNestedAttribute{Computed: true, NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{"comment": schema.StringAttribute{Computed: true}, "model": schema.StringAttribute{MarkdownDescription: "Node model, if available", Computed: true}, "node_alias": schema.StringAttribute{MarkdownDescription: "Node alias. User-assigned", Computed: true}, "topo_node_id": schema.StringAttribute{MarkdownDescription: "unique topology node ID. Generated by FM server", Computed: true}, "topo_node_type": schema.StringAttribute{MarkdownDescription: "indicates how node became a part of the topology graph", Computed: true}, "type": schema.StringAttribute{MarkdownDescription: "Annotation: type of a node. E.g. switch, router, etc...", Computed: true}, "vendor": schema.StringAttribute{MarkdownDescription: "Node vendor, if available", Computed: true}}}}, "model": schema.StringAttribute{Optional: true}, "node_alias": schema.StringAttribute{MarkdownDescription: "Aliases of the nodes", Optional: true}, "page": schema.StringAttribute{MarkdownDescription: "parentheses-enclosed pair of values in a (pageNo:pageSize) format. 'pageNo' is 1-based. If omitted, entire list of entities is returned. Defaults to (1:100) to prevent reading entire DB by accident", Optional: true}, "sort": schema.StringAttribute{MarkdownDescription: "parentheses-enclosed comma-separated list of entity attributes, optionally qualified with the sort order attribute. The default sort order is ASC. Example: sort=(aaa,bbb:ASC,ccc:DESC)", Optional: true}, "type": schema.StringAttribute{MarkdownDescription: "Type of nodes", Optional: true}, "vendor": schema.StringAttribute{Optional: true}}}
}

// Read fetches remote state into the data source model.
func (d *GetTopovizExternalDevicesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config GetTopovizExternalDevicesDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	d.readListRemote(ctx, &config, resp)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}

// readListRemote performs the paginated read HTTP exchange and decodes the response array into config. Extracted from Read so the request/response logic is unit-testable without a tfsdk.Config.
func (d *GetTopovizExternalDevicesDataSource) readListRemote(ctx context.Context, config *GetTopovizExternalDevicesDataSourceModel, resp *datasource.ReadResponse) {
	if d.client == nil {
		resp.Diagnostics.AddError("Client Not Configured", "The API client was not set on the resource. The provider Configure method must run before resource operations; this is a bug in the generated provider.")
		return
	}
	reqPath := "/topoviz/externalDevices"
	params := url.Values{}
	if !config.Category.IsNull() {
		params.Set("category", config.Category.ValueString())
	}
	if !config.DiscoveredType.IsNull() {
		params.Set("discoveredType", config.DiscoveredType.ValueString())
	}
	if !config.Type.IsNull() {
		params.Set("type", config.Type.ValueString())
	}
	if !config.NodeAlias.IsNull() {
		params.Set("nodeAlias", config.NodeAlias.ValueString())
	}
	if !config.Model.IsNull() {
		params.Set("model", config.Model.ValueString())
	}
	if !config.Vendor.IsNull() {
		params.Set("vendor", config.Vendor.ValueString())
	}
	if !config.Page.IsNull() {
		params.Set("page", config.Page.ValueString())
	}
	if !config.Sort.IsNull() {
		params.Set("sort", config.Sort.ValueString())
	}
	var nextURL string
	fetch := func(ctx context.Context, p url.Values) (*http.Response, error) {
		httpReq, err := d.client.NewRequest(ctx, http.MethodGet, reqPath, nil)
		if err != nil {
			return nil, err
		}
		if nextURL != "" {
			parsed, perr := url.Parse(nextURL)
			if perr != nil {
				return nil, perr
			}
			httpReq.URL = parsed
		} else {
			httpReq.URL.RawQuery = p.Encode()
		}
		return d.client.Do(httpReq)
	}
	pages, err := client.ListAllPages(ctx, params, fetch, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading gigavuecore_get_topoviz_external_devices", fmt.Sprintf("Could not read list response: %s", err))
		return
	}
	items := []any{}
	for _, page := range pages {
		pageItems := []any{}
		dec := json.NewDecoder(bytes.NewReader(page))
		dec.UseNumber()
		if err := dec.Decode(&pageItems); err != nil {
			resp.Diagnostics.AddError("Error reading gigavuecore_get_topoviz_external_devices", fmt.Sprintf("Could not decode list page: %s", err))
			return
		}
		items = append(items, pageItems...)
	}
	if err := applyJSONToModel(&config, map[string]any{"items": items}); err != nil {
		resp.Diagnostics.AddError("Error reading gigavuecore_get_topoviz_external_devices", fmt.Sprintf("Could not map response to state: %s", err))
		return
	}
}

// Configure stores the API client supplied by the provider.
func (d *GetTopovizExternalDevicesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData))
		return
	}
	d.client = c
}
